// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideTab: typeof import('./src/components/aside-tab.vue')['default']
    AsideTabHeader: typeof import('./src/components/aside-tab-header.vue')['default']
    AsideTabItem: typeof import('./src/components/aside-tab-item.vue')['default']
    CategoryItem: typeof import('./src/components/category-item.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ListItemV1: typeof import('./src/components/list-item-v1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopHeader: typeof import('./src/components/top-header.vue')['default']
  }
}
